#ifdef verify 
#undef verify 
#endif 
#ifdef check 
#undef check 
#endif 
#undef PROTOBUF_USE_DLLS 
#define PROTOBUF_USE_DLLS 0 
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum ClassType : int {
  CLASS_NONE = 0,
  ASSASSIN = 1,
  CLERIC = 2,
  RANGER = 3,
  TEMPLAR = 4,
  ClassType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ClassType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ClassType_IsValid(int value);
constexpr ClassType ClassType_MIN = CLASS_NONE;
constexpr ClassType ClassType_MAX = TEMPLAR;
constexpr int ClassType_ARRAYSIZE = ClassType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ClassType_descriptor();
template<typename T>
inline const std::string& ClassType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ClassType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ClassType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ClassType_descriptor(), enum_t_value);
}
inline bool ClassType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ClassType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ClassType>(
    ClassType_descriptor(), name, value);
}
enum RoomStatus : int {
  RECRUITING = 0,
  IN_PROGRESS = 1,
  RoomStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  RoomStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool RoomStatus_IsValid(int value);
constexpr RoomStatus RoomStatus_MIN = RECRUITING;
constexpr RoomStatus RoomStatus_MAX = IN_PROGRESS;
constexpr int RoomStatus_ARRAYSIZE = RoomStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RoomStatus_descriptor();
template<typename T>
inline const std::string& RoomStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RoomStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RoomStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RoomStatus_descriptor(), enum_t_value);
}
inline bool RoomStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RoomStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RoomStatus>(
    RoomStatus_descriptor(), name, value);
}
enum DungeonFailReason : int {
  Ready = 0,
  FullDungeon = 1,
  DungeonFailReason_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DungeonFailReason_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DungeonFailReason_IsValid(int value);
constexpr DungeonFailReason DungeonFailReason_MIN = Ready;
constexpr DungeonFailReason DungeonFailReason_MAX = FullDungeon;
constexpr int DungeonFailReason_ARRAYSIZE = DungeonFailReason_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DungeonFailReason_descriptor();
template<typename T>
inline const std::string& DungeonFailReason_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DungeonFailReason>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DungeonFailReason_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DungeonFailReason_descriptor(), enum_t_value);
}
inline bool DungeonFailReason_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DungeonFailReason* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DungeonFailReason>(
    DungeonFailReason_descriptor(), name, value);
}
enum MailFailReason : int {
  NONE_ERROR = 0,
  NONE_RECEIVER = 1,
  NONE_GOLD = 2,
  NONE_ITEM = 3,
  MailFailReason_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MailFailReason_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MailFailReason_IsValid(int value);
constexpr MailFailReason MailFailReason_MIN = NONE_ERROR;
constexpr MailFailReason MailFailReason_MAX = NONE_ITEM;
constexpr int MailFailReason_ARRAYSIZE = MailFailReason_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MailFailReason_descriptor();
template<typename T>
inline const std::string& MailFailReason_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MailFailReason>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MailFailReason_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MailFailReason_descriptor(), enum_t_value);
}
inline bool MailFailReason_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MailFailReason* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MailFailReason>(
    MailFailReason_descriptor(), name, value);
}
enum EPvpState : int {
  PVP_STATE_INACTIVE = 0,
  PVP_STATE_WARN_START = 1,
  PVP_STATE_ACTIVE = 2,
  PVP_STATE_WARN_END = 3,
  EPvpState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EPvpState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EPvpState_IsValid(int value);
constexpr EPvpState EPvpState_MIN = PVP_STATE_INACTIVE;
constexpr EPvpState EPvpState_MAX = PVP_STATE_WARN_END;
constexpr int EPvpState_ARRAYSIZE = EPvpState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPvpState_descriptor();
template<typename T>
inline const std::string& EPvpState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EPvpState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EPvpState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EPvpState_descriptor(), enum_t_value);
}
inline bool EPvpState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EPvpState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EPvpState>(
    EPvpState_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::ClassType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ClassType>() {
  return ::Protocol::ClassType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::RoomStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::RoomStatus>() {
  return ::Protocol::RoomStatus_descriptor();
}
template <> struct is_proto_enum< ::Protocol::DungeonFailReason> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::DungeonFailReason>() {
  return ::Protocol::DungeonFailReason_descriptor();
}
template <> struct is_proto_enum< ::Protocol::MailFailReason> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::MailFailReason>() {
  return ::Protocol::MailFailReason_descriptor();
}
template <> struct is_proto_enum< ::Protocol::EPvpState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::EPvpState>() {
  return ::Protocol::EPvpState_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
