;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="GameplayCue.Hit.Ranger.Key#",NewTagName="GameplayCue.Hit.Ranger.KeyE")
+GameplayTagRedirects=(OldTagName="Ability.Monster.Chase",NewTagName="Ability.Monster.ST.Chase")
+GameplayTagRedirects=(OldTagName="GameplayCue.Hit.Cleric.LB",NewTagName="GameplayCue.Hit.Cleric.LB_1")
+GameplayTagRedirects=(OldTagName="Ability.Monster.TH.SummonColorOrb",NewTagName="Ability.Monster.TH.SummonColorOrb70")
+GameplayTagRedirects=(OldTagName="Ability.Monster.LT.EletricZone",NewTagName="Ability.Monster.LT.ElectricZone")
+GameplayTagRedirects=(OldTagName="Montage.Lutalis.ScytheAttack",NewTagName="Montage.Lutalis.Scythe")
+GameplayTagList=(Tag="Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Dash",DevComment="")
+GameplayTagList=(Tag="Ability.Glide",DevComment="")
+GameplayTagList=(Tag="Ability.GlideDash",DevComment="")
+GameplayTagList=(Tag="Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.Groggy",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.LT.BaseAttack1",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.LT.BaseAttack2",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.LT.Dead",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.LT.ElectricZone",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.LT.ElectricZonePrepare",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.LT.JumpAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.LT.PT1",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.LT.Scythe",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.LT.ScytheAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.Rotation",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.ST.Chase",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.ST.Die",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.ST.PT1",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.ST.PT2",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.ST.PT3",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.ST.PT4",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.ChargeAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.CloseAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.Dead",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.MELEEAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.RangedAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.SeekShelter",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.SummonColorOrb",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.SummonColorOrb35",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.SummonColorOrb70",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.TeleportAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.TeleportCenter",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.WaveAttack",DevComment="")
+GameplayTagList=(Tag="Ability.StopGlide",DevComment="")
+GameplayTagList=(Tag="Combo.Available.KeyE",DevComment="")
+GameplayTagList=(Tag="Combo.Available.LB2",DevComment="")
+GameplayTagList=(Tag="Combo.Available.LB3",DevComment="")
+GameplayTagList=(Tag="Combo.Available.RB2",DevComment="")
+GameplayTagList=(Tag="Combo.Available.RB3",DevComment="")
+GameplayTagList=(Tag="Cooldown.Assassin.Key1",DevComment="")
+GameplayTagList=(Tag="Cooldown.Assassin.Key3",DevComment="")
+GameplayTagList=(Tag="Cooldown.Assassin.Key4",DevComment="")
+GameplayTagList=(Tag="Cooldown.Assassin.KeyQ",DevComment="")
+GameplayTagList=(Tag="Cooldown.Cleric.Key4",DevComment="")
+GameplayTagList=(Tag="Cooldown.Cleric.KeyE",DevComment="")
+GameplayTagList=(Tag="Cooldown.Cleric.KeyQ",DevComment="")
+GameplayTagList=(Tag="Cooldown.Monster.TH.ChargeAttack",DevComment="")
+GameplayTagList=(Tag="Cooldown.Monster.TH.TeleportAttack",DevComment="")
+GameplayTagList=(Tag="Cooldown.Monster.TH.WaveAttack",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ranger",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ranger.Key1",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ranger.Key2",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ranger.Key3",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ranger.Key4",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ranger.KeyE",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ranger.KeyQ",DevComment="")
+GameplayTagList=(Tag="Cooldown.Templar.Key1",DevComment="")
+GameplayTagList=(Tag="Cooldown.Templar.Key2",DevComment="")
+GameplayTagList=(Tag="Cooldown.Templar.Key3",DevComment="")
+GameplayTagList=(Tag="Cooldown.Templar.Key4",DevComment="")
+GameplayTagList=(Tag="Cooldown.Templar.KeyE",DevComment="")
+GameplayTagList=(Tag="Cooldown.Templar.KeyQ",DevComment="")
+GameplayTagList=(Tag="Data",DevComment="")
+GameplayTagList=(Tag="Data.AttackSlowDuration",DevComment="")
+GameplayTagList=(Tag="Data.Cooldown.Duration",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.GroggyDamage",DevComment="")
+GameplayTagList=(Tag="Data.HitManaRegen",DevComment="")
+GameplayTagList=(Tag="Data.ManaCost",DevComment="")
+GameplayTagList=(Tag="Event.CheckAttackHit",DevComment="")
+GameplayTagList=(Tag="Event.CheckAttackHit.Begin",DevComment="")
+GameplayTagList=(Tag="Event.CheckAttackHit.End",DevComment="")
+GameplayTagList=(Tag="Faction.Asmodian",DevComment="")
+GameplayTagList=(Tag="Faction.Elyos",DevComment="")
+GameplayTagList=(Tag="GameplayCue.GhostTrail",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.Key1",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.Key3",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.Key4",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.KeyE",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.KeyQ",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.LB",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.RB",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Cleric",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Cleric.Key4",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Cleric.KeyE",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Cleric.KeyQ",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Cleric.LB_1",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Cleric.LB_2",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Cleric.LB_3",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Monster.Lutalis.ElectricZone",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Monster.Lutalis.Scythe",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Monster.Siliator",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Monster.Siliator.Explosion",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Monster.Talythra",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Monster.Talythra.Projectile",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Monster.Talythra.Thunder",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.Key1",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.Key2",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.Key3",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.Key4",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.KeyE",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.KeyQ",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.LB",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.RB",DevComment="")
+GameplayTagList=(Tag="GamePlayCue.Hit.Templar.Key1",DevComment="")
+GameplayTagList=(Tag="GamePlayCue.Hit.Templar.Key2",DevComment="")
+GameplayTagList=(Tag="GamePlayCue.Hit.Templar.Key3",DevComment="")
+GameplayTagList=(Tag="GamePlayCue.Hit.Templar.Key4",DevComment="")
+GameplayTagList=(Tag="GamePlayCue.Hit.Templar.KeyE",DevComment="")
+GameplayTagList=(Tag="GamePlayCue.Hit.Templar.KeyQ",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Templar.LB",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Templar.RB",DevComment="")
+GameplayTagList=(Tag="Gimmick.Monster.TH.HP70",DevComment="")
+GameplayTagList=(Tag="Gimmick.Monster.TH.HP35.Done",DevComment="")
+GameplayTagList=(Tag="Gimmick.Monster.TH.HP35.Pending",DevComment="")
+GameplayTagList=(Tag="Gimmick.Monster.TH.HP70.Done",DevComment="")
+GameplayTagList=(Tag="Gimmick.Monster.TH.HP70.Pending",DevComment="")
+GameplayTagList=(Tag="Gimmick.Monster.TH.Shelter",DevComment="")
+GameplayTagList=(Tag="Montage.Lutalis.BaseAttack1",DevComment="")
+GameplayTagList=(Tag="Montage.Lutalis.BaseAttack2",DevComment="")
+GameplayTagList=(Tag="Montage.Lutalis.Dead",DevComment="")
+GameplayTagList=(Tag="Montage.Lutalis.ElectricZone",DevComment="")
+GameplayTagList=(Tag="Montage.Lutalis.Groggy",DevComment="")
+GameplayTagList=(Tag="Montage.Lutalis.JumpAttack",DevComment="")
+GameplayTagList=(Tag="Montage.Lutalis.PT1",DevComment="")
+GameplayTagList=(Tag="Montage.Lutalis.Scythe",DevComment="")
+GameplayTagList=(Tag="Montage.Siliator",DevComment="")
+GameplayTagList=(Tag="Montage.Siliator.Die",DevComment="")
+GameplayTagList=(Tag="Montage.Siliator.Groggy",DevComment="")
+GameplayTagList=(Tag="Montage.Siliator.PT1",DevComment="")
+GameplayTagList=(Tag="Montage.Siliator.PT2",DevComment="")
+GameplayTagList=(Tag="Montage.Siliator.PT3",DevComment="")
+GameplayTagList=(Tag="Montage.Siliator.PT4",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.ChargeAttack",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.CloseAttack",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.Dead",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.Groggy",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.RangedAttack",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.SeekShelter",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.SummonColorOrb",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.Teleport",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.TeleportAttack",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.WaveAttack",DevComment="")
+GameplayTagList=(Tag="Phase.Monster.Combat",DevComment="")
+GameplayTagList=(Tag="Phase.Monster.Dead",DevComment="")
+GameplayTagList=(Tag="Phase.Monster.Groggy",DevComment="")
+GameplayTagList=(Tag="Phase.Monster.OutofCombat",DevComment="")
+GameplayTagList=(Tag="Phase.Monster.PreCombat",DevComment="")
+GameplayTagList=(Tag="Phase.Monster.Reset",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Combat",DevComment="")
+GameplayTagList=(Tag="State.Dashing",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Gliding",DevComment="")
+GameplayTagList=(Tag="State.Groggy",DevComment="")
+GameplayTagList=(Tag="State.Jumping",DevComment="")
+GameplayTagList=(Tag="State.Monster.Groggy",DevComment="")
+GameplayTagList=(Tag="State.Monster.LT.Attack.Selected.JumpAttack",DevComment="")
+GameplayTagList=(Tag="State.Monster.LT.Attack.Selected.Normal",DevComment="")
+GameplayTagList=(Tag="State.Monster.LT.Attack.Selected.Scythe",DevComment="")
+GameplayTagList=(Tag="State.Monster.LT.BaseAttack1",DevComment="")
+GameplayTagList=(Tag="State.Monster.LT.Chase",DevComment="")
+GameplayTagList=(Tag="State.Monster.LT.Dead",DevComment="")
+GameplayTagList=(Tag="State.Monster.LT.ElectricZone",DevComment="")
+GameplayTagList=(Tag="State.Monster.LT.Idle",DevComment="")
+GameplayTagList=(Tag="State.Monster.LT.ScytheAttack",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.ChargeAttack",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.Chase",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.Dead",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.Idle",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.RangedShot",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.SeekShelter",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.SummonColorOrb",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.TeleportAttack",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.TeleportToCenter",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.WaveAttack",DevComment="")
+GameplayTagList=(Tag="State.Sprint",DevComment="")
+GameplayTagList=(Tag="Team.Daeva",DevComment="")
+GameplayTagList=(Tag="Team.Monster",DevComment="")

